# Generated by Django 6.0.3 on 2026-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0002_alter_filerecord_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='operation',
            field=models.CharField(choices=[('merge', 'Merge PDF'), ('split', 'Split PDF'), ('compress_pdf', 'Compress PDF'), ('word_to_pdf', 'Word to PDF'), ('pdf_to_word', 'PDF to Word'), ('images_to_pdf', 'Images to PDF'), ('remove_pages', 'Remove Pages')], max_length=20),
        ),
    ]
